name: Hello World
author: Shimul Kumar Saha
description: Greet someone and record the time

inputs:
  who_to_greet:
    description: Who to greet
    default: Shimul    
outputs:
  time:
    description: The time of the greeting

runs:
  using: "Docker"
  image: "Dockerfile"
  args:
    - ${{ inputs.who_to_greet }}
  env:
    HELLO: WORLD 
  post-entrypoint: "cleanup.sh"
  post-if: runner.os == 'linux'   
