name: Caches And Artifacts
on: [workflow_dispatch]


jobs:
  use-axios:
    runs-on: ubuntu
    steps:
      - uses: actions/checkout@v3
      - uses: actions/cache@v3
        name: Cache Dependencies
        id: cache-dependencies
        with:
          path: ~/.npm
          key: ${{ runner.os }}-npm-cache-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-mpm-cache-
            ${{ runner.os }}-  
      - name: Display Cache Output
        run: echo '${{ toJson(steps.cache-dependencies.outputs) }}'    
      - name: Install Dependencies
        run: npm install  
      - uses: actions/github-script@v6
        with:
          script: |
            const axios = required('axios');
            const res = await axios('https://icanhazdadjoke.com/', { headers: { Accept: 'text/plain' }});
            console.log(res.data);  
