name: Manually Triggered Workflow
on:
    workflow_dispatch:
        inputs:
            string:
                description: A string value
                default: Default Value
                type: string
                required: true
            options:
                description: Choose an option
                type: choice
                default: "Option Two"
                options:
                    - Option One
                    - Option Two
                    - Option Three
            environment:
                description: Choose an environment
                type: environment
                required: true
jobs:
    log_info:
        runs-on: ubuntu-latest
        steps:
            - run: |
                echo $GITHUB_REF
                echo "String: ${{ inputs.string }}"
                echo "String: ${{ inputs.options }}"
                echo "String: ${{ inputs.environment }}"                          