name: Status Check Functions Workflow
on: [push]

jobs:
    job-1:
        runs-on: ubuntu-latest
        steps:
            - name: Step 1
              run: sleep 20
            - name: Step 2
              id: step-2
              run: exit 1
            - name: Run on Failure
              if: failure() && steps.step-2.conclusion == 'failure'
              run: echo "Run on Failure of Step 2" 
            - name: Run on Success
              run: echo "Run on Success"
            - name: Run Always
              if: always()
              run: echo "Run Always"     
            - name: Run on Cancelled
              if: cancelled()
              run: echo "Run on Cancelled"
    job-2:
        runs-on: ubuntu-latest
        needs: job-1
        if: failure()
        steps:
            - run: echo "Job 2"