name: Using Reusable Workflow
on:
  workflow_dispatch:
    inputs:
      name:
        description: Whats your name
        type: string
        required: true
        default: 'Shimul'
jobs:
  call-reusable-workflow:
    uses: ./.github/workflows/reusable-workflow.yaml
    with:
      name: ${{ inputs.name }}
    secrets:
      access_token: ${{ secrets.ACCESS_TOKEN }}  
  using-reusable-workflow-output:
    runs-on: ubuntu-latest
    needs: call-reusable-workflow
    steps:
      - name: Display Reusable Workflow Output
        run: echo '${{ needs.call-reusable-workflow.outputs.date }}'